language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
  - 7.0

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

before_script:
  - composer install --dev --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - phpunit -c travis.phpunit.xml
  - php vendor/bin/coveralls -c .coveralls.yml -v
